name: mirrulations-testing
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup_environment@latest

      - name: Execute Makefile Unit Tests 
        # this works without .venv because the Makefile modifies the path to use the venv - see Makefile line 4
        run: make static
